### PR TITLE
added analysis fire feature

### PR DESCRIPTION
**Pull request by pshassett**
Moved analysis to a new branch to keep PR focused.  Extended testing for increased coverage. I am still using the unittest mock class in test_fire.py because it provides more independence between units under test and functionality that they rely on. So python 2.7 builds on travis will fail.

I think the mock class is a tool that can be very useful for future tests.  We should think about how important reverse-compatibility with those older versions is and how we can incorporate new language/library features that come up over time.

### CODE REVIEW

**Comment by pshassett** [comment]
It looks like pandas relies on [tables](https://pypi.org/project/tables/) for reading/writing hdf5 files.  Is there any way this package can be added to the travis testing environment?

**Comment by kaklise** [comment]
You can add tables to the ci files, it will become an optional dependency of WNTR (import in try/except blocks).  I suggest saving files as simple text files and have an option to save files as hdf5.

**Comment by pshassett** [comment]
The hdf output is optional.  As long as pandas is a hard dependency of WNTR it would be nice to be able to use it to its full capability.

**Comment by pshassett** [comment]
`Doctest: resultsobject.rst ... FAIL` for py27min and py34 builds. Expecting `dtype: float32` gets `dtype: float64`.  Both are using Scipy 0.18.

**Pull request closed without merging**
